EMPTY_BASKET_MSG_BY_LANG = {
    'ar': 'سلة التسوق فارغة',
    'ca': 'La seva cistella està buida.',
    'cs': 'Váš košík je prázdný.',
    'da': 'Din indkøbskurv er tom.',
    'de': 'Ihr Warenkorb ist leer.',
    'en-gb': 'Your basket is empty.',
    'el': 'Το καλάθι σας είναι άδειο.',
    'es': 'Tu carrito esta vacío.',
    'fi': 'Korisi on tyhjä',
    'fr': 'Votre panier est vide.',
    'it': 'Il tuo carrello è vuoto.',
    'ko': '장바구니가 비었습니다.',
    'nl': 'Je winkelmand is leeg',
    'pl': 'Twój koszyk jest pusty.',
    'pt': 'O carrinho está vazio.',
    'pt-br': 'Sua cesta está vazia.',
    'ro': 'Cosul tau este gol.',
    'ru': 'Ваша корзина пуста',
    'sk': 'Váš košík je prázdny',
    'uk': 'Ваш кошик пустий.',
    'zh-cn': 'Your basket is empty.',
}
